name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Latest Version
        run: |
           VERSION=$(tail -n 2 VERSIONS | tr -d '[:space:]')
           echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/aws-backend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/aws-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}
            docker run -d \
              --name backend \
              -p 3001:3000 \
              --env-file /var/www/html/aws-backend/.env \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}
            docker image prune -f