name: Deploy to AWS EC2

on:
  push: 
   branches:
     - main
   tag:
     - 'v*.*.*' #TRIGGER ON IMANES TAG PUSH 
       
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set Docker Image Tag based on git commit SHA
      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        

      - name: Login to Docker H54.163.18.220ub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/aws-backend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/aws-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Stop and remove old container
            docker stop backend || true
            docker rm backend || true

            # Remove old image (optional)
            docker rmi ${{ secrets.DOCKER_USERNAME }}/aws-backend:latest || true

            # Pull new versioned image
            docker pull ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}

            # Run container with versioned image
            docker run -d \
              --name backend \
              -p 3000:3000 \
              --env-file /var/www/html/aws-backend/.env \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/aws-backend:${{ env.IMAGE_TAG }}

            # Clean up unused images
            docker image prune -f